version: '3.8'
name: cloud-ec2-app

services:
  # This builds YOUR Node.js app using the Dockerfile in the current folder
  backend:
    container_name: cloud-backend
    image: 541890559721.dkr.ecr.us-east-1.amazonaws.com/reuseiteso-backend:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/iteso_db
    depends_on:
      - database
    env_file:
      - .env

  # This pulls the OFFICIAL MongoDB image (no Dockerfile needed for this)
  database:
    container_name: cloud-database
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

# This is the "Magic" that saves your data on the EC2 hard drive
volumes:
  mongo-data: