### Registro
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nombre": "Danie Manuelito",
  "email": "H_gdanielpatron@hotmail.com",
  "contrasena": "64321"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "valenzuela@hotmail.com",
  "contrasena": "654321"
}

### Perfil
GET http://localhost:3000/auth/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjNhNTIyZDU0MTgyZDcwMWRiZDQ0YiIsImVtYWlsIjoibGVvX2RhbmkyMDAwQGhvdG1haWwuY29tIiwicm9sIjoidXN1YXJpbyIsImlhdCI6MTc0NzE3MDYyMCwiZXhwIjoxNzQ3MTc0MjIwfQ.QCJm5xEyydQ8KFVVDjSQHK3rajImQE-m-3crFvQtB9E