### Registro
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nombre": "Danie Manuelito",
  "email": "H_gdanielpatron@hotmail.com",
  "contrasena": "64321"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "valenzuela@hotmail.com",
  "contrasena": "654321"
}

### Perfil
GET http://localhost:3000/auth/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGZlYjZjYTU1NTIzNzliZDQ5M2ExYyIsImVtYWlsIjoidmFsZW56dWVsYUBob3RtYWlsLmNvbSIsInJvbCI6InVzdWFyaW8iLCJpYXQiOjE3NDU4NzM4MTYsImV4cCI6MTc0NTg3NzQxNn0.o_A5a6lQyXQlnOCG0FBm13ihhcd9bzFOSePadPeLqjc