sonar.projectKey=My-Ecommerce-ITESO
sonar.projectName=My-Ecommerce-ITESO
sonar.sources=src
sonar.language=ts
sonar.host.url=http://localhost:9000
sonar.login=sqp_6088f2a59290167cc2bdfa0493c7686d454d4dcb
# Qué carpetas NO escanear
sonar.exclusions=node_modules/**,dist/**,public/**,tests/**

# Incluir TS
sonar.inclusions=src/**/*.ts

# Reportar calidad
sonar.sourceEncoding=UTF-8
